apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: udacity-app
    spec:
      containers:
        - image: aguiljc/udacity:latest
          name: udacity-app
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: udacity-app
spec:
  type: NodePort
  selector:
    app: udacity-app
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 30100