version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:

  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build, tag and push docker image to docker.io
          command: |
            docker login -u aguiljc -p ${DOCKERHUB_PASSWORD}
            docker build -t aguiljc/udacity:${CIRCLE_WORKFLOW_ID:0:7} .
            docker push aguiljc/udacity:${CIRCLE_WORKFLOW_ID:0:7}
            docker tag aguiljc/udacity:${CIRCLE_WORKFLOW_ID:0:7} aguiljc/udacity:latest
            docker push aguiljc/udacity:latest
workflows:
  default:
    jobs:
      - lint-container
      - build-container:
         requires: [lint-container]
      - publish-latest:
         requires: [new-build-container]
