# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

orbs:
  docker: circleci/docker@2.1.2
  kubernetes: circleci/kubernetes@1.3.1
  aws-eks: circleci/aws-eks@0.2.3

jobs:

  lint-container:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo     
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            make install
      - run:
          name: run lint
          command: |
              make lint 

  build-push-container:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: aguiljc/udacity
          tag: "1.2"
      - docker/push:
          digest-path: /tmp/digest.txt
          image: aguiljc/udacity
          tag: "1.2"
      - run:
          command: |
            echo "This is the path: $(</tmp/digest.txt)"

workflows:
  default:
    jobs:
      - lint-container
      - build-push-container:
         requires: [lint-container]
