orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: ndukwearm19docker/docker-node-app
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: circleci/node:latest
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD

jobs:
    publishLatestToHub: 
      executor: docker-publisher
 
      steps: 
        - checkout
        - setup_remote_docker
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              docker login -u "$DOCKER_USER" -p "$DOCKERHUB_PASSWORD" docker.io
              docker build -t $IMAGE_NAME .
              docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
       - publishLatestToHub

# # Python CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-python/ for more details
# #
# version: 2.1

# executors:
#   docker-publisher:
#     environment:
#       IMAGE_NAME: aguiljc/udacity
#     docker:
#       - image: cimg/base:2021.04 
#         auth:
#           username: $DOCKER_USERNAME
#           password: $DOCKERHUB_PASSWORD
#   python:
#     docker:
#       - image: circleci/python:3.7.3-stretch
#   aws:
#     docker:
#       - image: amazon/aws-cli

# orbs:
#   docker: circleci/docker@2.1.2
#   kubernetes: circleci/kubernetes@1.3.1
#   aws-eks: circleci/aws-eks@0.2.3

# jobs:

#   lint-container:
#     docker:
#       - image: python:3.7.3-stretch
#     working_directory: ~/repo     
#     steps:
#       - checkout
#       - run:
#           name: install dependencies
#           command: |
#             make install
#       - run:
#           name: run lint
#           command: |
#               make lint 

#   # build-container:
#   #   executor: docker/docker
#   #   working_directory: ~/app
#   #   steps:
#   #    - checkout
#   #    - run: 
#   #       name: Build and push the docker container
#   #       command:
#   #         echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKER_USER --password-stdin #|
#   #         # docker build -t aguiljc/udacity . |
#   #         # docker push udacity:latest # |
#   #         # docker tag aguiljc/udacity aguiljc/udacity:latest

#   new-build-container:
#     executor: docker/docker
#     steps:
#       - setup_remote_docker
#       - checkout
#       - docker/check
#       - docker/build:
#           image: aguiljc/udacity
#           tag: "1.2"
#       - docker/push:
#           digest-path: /tmp/digest.txt
#           image: aguiljc/udacity
#           tag: "1.2"
#       - run:
#           command: |
#             echo "This is the path: $(</tmp/digest.txt)"

#   # publish-latest:
#   #   executor: docker/docker
#   #   steps:
#   #     - attach_workspace:
#   #         at: /tmp/workspace
#   #     - setup_remote_docker
#   #     - run:
#   #         name: Load archived Docker image
#   #         command: docker load -i /tmp/workspace/image.tar
#   #     - run:
#   #         name: Publish Docker Image to Docker Hub
#   #         command: |
#   #           docker push $IMAGE_NAME:latest

# workflows:
#   default:
#     jobs:
#       - lint-container
#       - new-build-container:
#          requires: [lint-container]
#       # - publish-latest:
#       #    requires: [new-build-container]
