# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  docker: circleci/docker@2.0.1
  kubernetes: circleci/kubernetes@0.12.0
  aws-eks: circleci/aws-eks@0.2.3

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo     
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            make install

#  Should not need to install hadolint as its in makefile
#             # Install hadolint
#             wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
#             chmod +x /bin/hadolint


#       # run lint!
#       - run:
#           name: run lint
#           command: |
#               . venv/bin/activate
#               make lint 